In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
df=pd.read_csv('../data/Telco_customer_churn.csv')

In [130]:
df.head(3)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved

In [131]:
drop_cols = [
    "CustomerID",
    "Count",
    "Country",
    "State",
    "City",
    "Zip Code",
    "Lat Long",
    "Latitude",
    "Longitude",
    "Churn Label",
    "Churn Score",
    "CLTV",
    "Churn Reason"
]

df=df.drop(columns=drop_cols)

In [132]:
df.head(3)

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,1

In [133]:
categorical_cols = df.select_dtypes(include='object').columns
print("Categorical columns:", categorical_cols,"unique values:",df[categorical_cols].nunique())

Categorical columns: Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Total Charges'],
      dtype='object') unique values: Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Total Charges        6531
dtype: int64

In [134]:
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors='coerce')

In [135]:
df["Total Charges"] = df["Total Charges"].fillna(np.median(df["Total Charges"]))

In [136]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1

In [137]:
df.columns = df.columns.str.replace(" ", "_")

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             7043 non-null   object
 1   Senior_Citizen     7043 non-null   object
 2   Partner            7043 non-null   object
 3   Dependents         7043 non-null   object
 4   Tenure_Months      7043 non-null   int64
 5   Phone_Service      7043 non-null   object
 6   Multiple_Lines     7043 non-null   object
 7   Internet_Service   7043 non-null   object
 8   Online_Security    7043 non-null   object
 9   Online_Backup      7043 non-null   object
 10  Device_Protection  7043 non-null   object
 11  Tech_Support       7043 non-null   object
 12  Streaming_TV       7043 non-null   object
 13  Streaming_Movies   7043 non-null   object
 14  Contract           7043 non-null   object
 15  Paperless_Billing  7043 non-null   object
 16  Payment_Method     7043 non-null   object
 17  Monthly_Charges    7043 non-null   float64
 18  Total_Charges      7032 non-null   float64
 19  Churn_Value        7043 non-null   int64
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [139]:
categorical_cols = df.select_dtypes(include='object').columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Categorical columns:", categorical_cols)
print("Numerical columns:", numerical_cols)
numerical_cols = numerical_cols.drop("Churn_Value")

Categorical columns: Index(['Gender', 'Senior_Citizen', 'Partner', 'Dependents', 'Phone_Service',
       'Multiple_Lines', 'Internet_Service', 'Online_Security',
       'Online_Backup', 'Device_Protection', 'Tech_Support', 'Streaming_TV',
       'Streaming_Movies', 'Contract', 'Paperless_Billing', 'Payment_Method'],
      dtype='object')
Numerical columns: Index(['Tenure_Months', 'Monthly_Charges', 'Total_Charges', 'Churn_Value'], dtype='object')

In [140]:
X=df.drop(columns=["Churn_Value"])

In [141]:
y=df["Churn_Value"]

In [142]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [143]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [144]:
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [145]:
preprocessor = ColumnTransformer([
    ("num", num_pipeline, numerical_cols),
    ("cat", cat_pipeline, categorical_cols)
])

In [146]:
X_transformed = preprocessor.fit_transform(X)

In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.2, random_state=42,stratify=y)

In [148]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()
log_model.fit(X_train, y_train)

LogisticRegression()

In [149]:
log_model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': 0.0,
 'max_iter': 100,
 'n_jobs': None,
 'penalty': 'deprecated',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [150]:
log_preds=log_model.predict(X_test)

In [ ]:
# Evaluate the model
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score
accuracy = accuracy_score(y_test, log_preds)
f1 = f1_score(y_test, log_preds)
recall = recall_score(y_test, log_preds)
precision = precision_score(y_test, log_preds)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Recall: {recall:.4f}")
print(f"Precision: {precision:.4f}")

Accuracy: 0.8006
F1 Score: 0.6025
Recall: 0.5695
Precision: 0.6396

In [153]:
import mlflow

mlflow.set_experiment("churn-prediction")
mlflow.set_tracking_uri("http://localhost:5000")
with mlflow.start_run(run_name="logistic_regression"):
    mlflow.log_param("model", "Logistic Regression")
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("f1_score", f1)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("precision", precision)
    mlflow.sklearn.log_model(log_model, "model")

2026/05/24 17:25:50 INFO mlflow.tracking.fluent: Experiment with name 'churn-prediction' does not exist. Creating a new experiment.
2026/05/24 17:25:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/24 17:25:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run logistic_regression at: http://localhost:5000/#/experiments/1/runs/988d1933441547be8a074d1052d12062
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [154]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [155]:
rf_preds=rf_model.predict(X_test)

In [156]:
print(rf_preds)

[0 1 0 ... 0 0 0]

In [157]:
accuracy = accuracy_score(y_test, rf_preds)
print(f"Random Forest Accuracy: {accuracy:.4f}")

f1 = f1_score(y_test, rf_preds)
print(f"Random Forest F1 Score: {f1:.4f}")

recall = recall_score(y_test, rf_preds)
print(f"Random Forest Recall: {recall:.4f}")

precision = precision_score(y_test, rf_preds)
print(f"Random Forest Precision: {precision:.4f}")

Random Forest Accuracy: 0.7857
Random Forest F1 Score: 0.5546
Random Forest Recall: 0.5027
Random Forest Precision: 0.6184

In [158]:
mlflow.set_experiment("churn-prediction")
mlflow.set_tracking_uri("http://localhost:5000")
with mlflow.start_run(run_name="random_forest"):
    mlflow.log_param("model", "Random Forest")
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("f1_score", f1)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("precision", precision)
    mlflow.sklearn.log_model(rf_model, "model")

2026/05/24 17:31:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/24 17:31:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run random_forest at: http://localhost:5000/#/experiments/1/runs/2f248f500ed849bbb908bd69ec8d5b50
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [159]:
# gradient boosting
from sklearn.ensemble import GradientBoostingClassifier
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [160]:
gd_preds=gb_model.predict(X_test)

In [161]:
accuracy = accuracy_score(y_test, gd_preds)
print(f"Gradient Boosting Accuracy: {accuracy:.4f}")

f1 = f1_score(y_test, gd_preds)
print(f"Gradient Boosting F1 Score: {f1:.4f}")

recall = recall_score(y_test, gd_preds)
print(f"Gradient Boosting Recall: {recall:.4f}")
precision = precision_score(y_test, gd_preds)
print(f"Gradient Boosting Precision: {precision:.4f}")

Gradient Boosting Accuracy: 0.7984
Gradient Boosting F1 Score: 0.5836
Gradient Boosting Recall: 0.5321
Gradient Boosting Precision: 0.6461

In [162]:
mlflow.set_experiment("churn-prediction")
mlflow.set_tracking_uri("http://localhost:5000")
with mlflow.start_run(run_name="gradient_boosting"):
    mlflow.log_param("gd_model", "Gradient Boosting")
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("f1_score", f1)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("precision", precision)
    mlflow.sklearn.log_model(gb_model, "model")

2026/05/24 17:36:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/24 17:36:42 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run gradient_boosting at: http://localhost:5000/#/experiments/1/runs/c6eb510f037847efa2d6cdc8b4168c4b
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [163]:
import joblib
joblib.dump(log_model, "../models/logistic_regression_model.pkl")
joblib.dump(rf_model, "../models/random_forest_model.pkl")
joblib.dump(gb_model, "../models/gradient_boosting_model.pkl")
joblib.dump(preprocessor, "../models/preprocessor.pkl")

['../models/preprocessor.pkl']